spring:
  security:
    jwt:
      key: abcdefghijklmn
      expire: 7

  mail:
    host: smtp.163.com
    password: WPEUJPCKOTXJHWKM
    username: redis_validate_007@163.com
    port: 465
    properties:
      from: redis_validate_007@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    username: root
    addresses: 192.168.75.129
    password: 20011118
    port: 5672

  datasource:
    url: jdbc:mysql://localhost:3306/jwt?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 20011118
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 192.168.75.129
      client-type: lettuce

