spring:
  security:
    jwt:
      key: abcdefghijklmn
      expire: 7

  datasource:
    url: jdbc:mysql://localhost:3306/jwt?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 20011118
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 192.168.75.133
      client-type: lettuce
      password: 20011118
